### ISSUE TITLE
Meta attributes missing in Report Document's Meta

### ISSUE THREAD

**Issue by fredorange** [chb/indivo_server#1]
### The following attributes are missing in the document meta when you get the document within a Report [_GET http://indivo/records/recid/reports/minimal/vitals/_]:

```
Record_id
RelatesTo
IsRelatedFrom
```

It is ok with [_GET http://indivo/records/recid/documents/docid/meta_].

Indivo beta 3.

**Comment by thisisdhaas** [comment]
I've taken a look at this, and it appears to be an issue with the template loader's context when using the custom templatetag 'get_doc_obj' that is used by the reporting calls. The GET documents/{id}/meta call doesn't use this tag, which explains the behavior.

I'll try to get a fix out this week for this.
